# Generated by Django 3.1.3 on 2023-07-07 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionItem', '0030_auto_20201127_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='year_published',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 9, 52, 55, 924996)),
        ),
    ]
